#ifndef _PACKOFFSETS_H
#define _PACKOFFSETS_H

enum {
  MSG_DATA_OFFSET = 5
};

enum {
  TOSH_DATA_LENGTH = 29,
  UPACK_MSG_OFFSET = 1,
  UPACK_DATA_LEN = TOSH_DATA_LENGTH - UPACK_MSG_OFFSET,
  UPACK_MSG_DATA_LEN = UPACK_DATA_LEN - MSG_DATA_OFFSET
};

#endif // _PACKOFFSETS_H
