#!/bin/bash
ct="java edu.rice.compass.CompassTools"
for dest in `seq $1 $2`;
do
  $ct -o -d $dest -c
done
for src in `seq $1 $2`;
do
  [ ! -e "src$src" ] && mkdir src$src
  $ct -o -d $src --power $3
  $ct -o -d $src --ping 250
  sleep 10
  $ct -o -d $src --power 31
  for dest in `seq $1 $2`;
  do
    $ct --stats -d $dest `cygpath -w $PWD/src$src/$dest.xml`
    $ct -o -d $dest -c
  done
done
