/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'UnicastPack'
 * message type.
 */

package edu.rice.compass;

public class UnicastPack extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 29;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 6;

    /** Create a new UnicastPack of size 29. */
    public UnicastPack() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new UnicastPack of the given data_length. */
    public UnicastPack(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack with the given data_length
     * and base offset.
     */
    public UnicastPack(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack using the given byte array
     * as backing store.
     */
    public UnicastPack(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack using the given byte array
     * as backing store, with the given base offset.
     */
    public UnicastPack(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public UnicastPack(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack embedded in the given message
     * at the given base offset.
     */
    public UnicastPack(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new UnicastPack embedded in the given message
     * at the given base offset and length.
     */
    public UnicastPack(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <UnicastPack> \n";
      try {
        s += "  [retriesLeft=0x"+Long.toHexString(get_retriesLeft())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.src=0x"+Long.toHexString(get_data_src())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.dest=0x"+Long.toHexString(get_data_dest())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.type=0x"+Long.toHexString(get_data_type())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.moteCmd.cmd=0x"+Long.toHexString(get_data_data_moteCmd_cmd())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.raw.value=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_raw_value(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wData.dataSet=0x"+Long.toHexString(get_data_data_wData_dataSet())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wData.level=0x"+Long.toHexString(get_data_data_wData_level())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wData.state=0x"+Long.toHexString(get_data_data_wData_state())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wData.value=";
        for (int i = 0; i < 2; i++) {
          s += Float.toString(getElement_data_data_wData_value(i))+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.level=0x"+Long.toHexString(get_data_data_wConfData_level())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.packNum=0x"+Long.toHexString(get_data_data_wConfData_packNum())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.moteCount=0x"+Long.toHexString(get_data_data_wConfData_moteCount())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.moteConf.id=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_wConfData_moteConf_id(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.moteConf.state=";
        for (int i = 0; i < 3; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_wConfData_moteConf_state(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfData.moteConf.coeff=";
        for (int i = 0; i < 3; i++) {
          s += Float.toString(getElement_data_data_wConfData_moteConf_coeff(i))+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfHeader.numLevels=0x"+Long.toHexString(get_data_data_wConfHeader_numLevels())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wConfHeader.nbCount=";
        for (int i = 0; i < 10; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_wConfHeader_nbCount(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wState.state=0x"+Long.toHexString(get_data_data_wState_state())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.wState.dataSetTime=0x"+Long.toHexString(get_data_data_wState_dataSetTime())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.rcvd=0x"+Long.toHexString(get_data_data_stats_rcvd())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.rssi="+Float.toString(get_data_data_stats_rssi())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.sent=0x"+Long.toHexString(get_data_data_stats_sent())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.acked=0x"+Long.toHexString(get_data_data_stats_acked())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.numReps=0x"+Long.toHexString(get_data_data_stats_numReps())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.reports.type=";
        for (int i = 0; i < 2; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_stats_reports_type(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.reports.data.cache.level=";
        for (int i = 0; i < 2; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_stats_reports_data_cache_level(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.reports.data.cache.mote=";
        for (int i = 0; i < 2; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_stats_reports_data_cache_mote(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [data.data.stats.reports.number=";
        for (int i = 0; i < 2; i++) {
          s += "0x"+Long.toHexString(getElement_data_data_stats_reports_number(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: retriesLeft
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'retriesLeft' is signed (false).
     */
    public static boolean isSigned_retriesLeft() {
        return false;
    }

    /**
     * Return whether the field 'retriesLeft' is an array (false).
     */
    public static boolean isArray_retriesLeft() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'retriesLeft'
     */
    public static int offset_retriesLeft() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'retriesLeft'
     */
    public static int offsetBits_retriesLeft() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'retriesLeft'
     */
    public short get_retriesLeft() {
        return (short)getUIntElement(offsetBits_retriesLeft(), 8);
    }

    /**
     * Set the value of the field 'retriesLeft'
     */
    public void set_retriesLeft(short value) {
        setUIntElement(offsetBits_retriesLeft(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'retriesLeft'
     */
    public static int size_retriesLeft() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'retriesLeft'
     */
    public static int sizeBits_retriesLeft() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.src
    //   Field type: int
    //   Offset (bits): 8
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.src' is signed (false).
     */
    public static boolean isSigned_data_src() {
        return false;
    }

    /**
     * Return whether the field 'data.src' is an array (false).
     */
    public static boolean isArray_data_src() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.src'
     */
    public static int offset_data_src() {
        return (8 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.src'
     */
    public static int offsetBits_data_src() {
        return 8;
    }

    /**
     * Return the value (as a int) of the field 'data.src'
     */
    public int get_data_src() {
        return (int)getUIntElement(offsetBits_data_src(), 16);
    }

    /**
     * Set the value of the field 'data.src'
     */
    public void set_data_src(int value) {
        setUIntElement(offsetBits_data_src(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.src'
     */
    public static int size_data_src() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.src'
     */
    public static int sizeBits_data_src() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.dest
    //   Field type: int
    //   Offset (bits): 24
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.dest' is signed (false).
     */
    public static boolean isSigned_data_dest() {
        return false;
    }

    /**
     * Return whether the field 'data.dest' is an array (false).
     */
    public static boolean isArray_data_dest() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.dest'
     */
    public static int offset_data_dest() {
        return (24 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.dest'
     */
    public static int offsetBits_data_dest() {
        return 24;
    }

    /**
     * Return the value (as a int) of the field 'data.dest'
     */
    public int get_data_dest() {
        return (int)getUIntElement(offsetBits_data_dest(), 16);
    }

    /**
     * Set the value of the field 'data.dest'
     */
    public void set_data_dest(int value) {
        setUIntElement(offsetBits_data_dest(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.dest'
     */
    public static int size_data_dest() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.dest'
     */
    public static int sizeBits_data_dest() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.type
    //   Field type: short
    //   Offset (bits): 40
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.type' is signed (false).
     */
    public static boolean isSigned_data_type() {
        return false;
    }

    /**
     * Return whether the field 'data.type' is an array (false).
     */
    public static boolean isArray_data_type() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.type'
     */
    public static int offset_data_type() {
        return (40 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.type'
     */
    public static int offsetBits_data_type() {
        return 40;
    }

    /**
     * Return the value (as a short) of the field 'data.type'
     */
    public short get_data_type() {
        return (short)getUIntElement(offsetBits_data_type(), 8);
    }

    /**
     * Set the value of the field 'data.type'
     */
    public void set_data_type(short value) {
        setUIntElement(offsetBits_data_type(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.type'
     */
    public static int size_data_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.type'
     */
    public static int sizeBits_data_type() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.moteCmd.cmd
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.moteCmd.cmd' is signed (false).
     */
    public static boolean isSigned_data_data_moteCmd_cmd() {
        return false;
    }

    /**
     * Return whether the field 'data.data.moteCmd.cmd' is an array (false).
     */
    public static boolean isArray_data_data_moteCmd_cmd() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.moteCmd.cmd'
     */
    public static int offset_data_data_moteCmd_cmd() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.moteCmd.cmd'
     */
    public static int offsetBits_data_data_moteCmd_cmd() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'data.data.moteCmd.cmd'
     */
    public short get_data_data_moteCmd_cmd() {
        return (short)getUIntElement(offsetBits_data_data_moteCmd_cmd(), 8);
    }

    /**
     * Set the value of the field 'data.data.moteCmd.cmd'
     */
    public void set_data_data_moteCmd_cmd(short value) {
        setUIntElement(offsetBits_data_data_moteCmd_cmd(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.moteCmd.cmd'
     */
    public static int size_data_data_moteCmd_cmd() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.moteCmd.cmd'
     */
    public static int sizeBits_data_data_moteCmd_cmd() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.raw.value
    //   Field type: int[]
    //   Offset (bits): 48
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.raw.value' is signed (false).
     */
    public static boolean isSigned_data_data_raw_value() {
        return false;
    }

    /**
     * Return whether the field 'data.data.raw.value' is an array (true).
     */
    public static boolean isArray_data_data_raw_value() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.raw.value'
     */
    public static int offset_data_data_raw_value(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.raw.value'
     */
    public static int offsetBits_data_data_raw_value(int index1) {
        int offset = 48;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 16;
        return offset;
    }

    /**
     * Return the entire array 'data.data.raw.value' as a int[]
     */
    public int[] get_data_data_raw_value() {
        int[] tmp = new int[3];
        for (int index0 = 0; index0 < numElements_data_data_raw_value(0); index0++) {
            tmp[index0] = getElement_data_data_raw_value(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.raw.value' from the given int[]
     */
    public void set_data_data_raw_value(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_raw_value(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data.data.raw.value'
     */
    public int getElement_data_data_raw_value(int index1) {
        return (int)getUIntElement(offsetBits_data_data_raw_value(index1), 16);
    }

    /**
     * Set an element of the array 'data.data.raw.value'
     */
    public void setElement_data_data_raw_value(int index1, int value) {
        setUIntElement(offsetBits_data_data_raw_value(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.raw.value'
     */
    public static int totalSize_data_data_raw_value() {
        return (48 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.raw.value'
     */
    public static int totalSizeBits_data_data_raw_value() {
        return 48;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.raw.value'
     */
    public static int elementSize_data_data_raw_value() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.raw.value'
     */
    public static int elementSizeBits_data_data_raw_value() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data.data.raw.value'
     */
    public static int numDimensions_data_data_raw_value() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.raw.value'
     */
    public static int numElements_data_data_raw_value() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data.data.raw.value'
     * for the given dimension.
     */
    public static int numElements_data_data_raw_value(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wData.dataSet
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wData.dataSet' is signed (false).
     */
    public static boolean isSigned_data_data_wData_dataSet() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wData.dataSet' is an array (false).
     */
    public static boolean isArray_data_data_wData_dataSet() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wData.dataSet'
     */
    public static int offset_data_data_wData_dataSet() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wData.dataSet'
     */
    public static int offsetBits_data_data_wData_dataSet() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wData.dataSet'
     */
    public short get_data_data_wData_dataSet() {
        return (short)getUIntElement(offsetBits_data_data_wData_dataSet(), 8);
    }

    /**
     * Set the value of the field 'data.data.wData.dataSet'
     */
    public void set_data_data_wData_dataSet(short value) {
        setUIntElement(offsetBits_data_data_wData_dataSet(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wData.dataSet'
     */
    public static int size_data_data_wData_dataSet() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wData.dataSet'
     */
    public static int sizeBits_data_data_wData_dataSet() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wData.level
    //   Field type: short
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wData.level' is signed (false).
     */
    public static boolean isSigned_data_data_wData_level() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wData.level' is an array (false).
     */
    public static boolean isArray_data_data_wData_level() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wData.level'
     */
    public static int offset_data_data_wData_level() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wData.level'
     */
    public static int offsetBits_data_data_wData_level() {
        return 56;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wData.level'
     */
    public short get_data_data_wData_level() {
        return (short)getUIntElement(offsetBits_data_data_wData_level(), 8);
    }

    /**
     * Set the value of the field 'data.data.wData.level'
     */
    public void set_data_data_wData_level(short value) {
        setUIntElement(offsetBits_data_data_wData_level(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wData.level'
     */
    public static int size_data_data_wData_level() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wData.level'
     */
    public static int sizeBits_data_data_wData_level() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wData.state
    //   Field type: short
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wData.state' is signed (false).
     */
    public static boolean isSigned_data_data_wData_state() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wData.state' is an array (false).
     */
    public static boolean isArray_data_data_wData_state() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wData.state'
     */
    public static int offset_data_data_wData_state() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wData.state'
     */
    public static int offsetBits_data_data_wData_state() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wData.state'
     */
    public short get_data_data_wData_state() {
        return (short)getUIntElement(offsetBits_data_data_wData_state(), 8);
    }

    /**
     * Set the value of the field 'data.data.wData.state'
     */
    public void set_data_data_wData_state(short value) {
        setUIntElement(offsetBits_data_data_wData_state(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wData.state'
     */
    public static int size_data_data_wData_state() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wData.state'
     */
    public static int sizeBits_data_data_wData_state() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wData.value
    //   Field type: float[]
    //   Offset (bits): 72
    //   Size of each element (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wData.value' is signed (false).
     */
    public static boolean isSigned_data_data_wData_value() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wData.value' is an array (true).
     */
    public static boolean isArray_data_data_wData_value() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wData.value'
     */
    public static int offset_data_data_wData_value(int index1) {
        int offset = 72;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 32;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wData.value'
     */
    public static int offsetBits_data_data_wData_value(int index1) {
        int offset = 72;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 32;
        return offset;
    }

    /**
     * Return the entire array 'data.data.wData.value' as a float[]
     */
    public float[] get_data_data_wData_value() {
        float[] tmp = new float[2];
        for (int index0 = 0; index0 < numElements_data_data_wData_value(0); index0++) {
            tmp[index0] = getElement_data_data_wData_value(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.wData.value' from the given float[]
     */
    public void set_data_data_wData_value(float[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_wData_value(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a float) of the array 'data.data.wData.value'
     */
    public float getElement_data_data_wData_value(int index1) {
        return (float)getFloatElement(offsetBits_data_data_wData_value(index1), 32);
    }

    /**
     * Set an element of the array 'data.data.wData.value'
     */
    public void setElement_data_data_wData_value(int index1, float value) {
        setFloatElement(offsetBits_data_data_wData_value(index1), 32, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.wData.value'
     */
    public static int totalSize_data_data_wData_value() {
        return (64 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.wData.value'
     */
    public static int totalSizeBits_data_data_wData_value() {
        return 64;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.wData.value'
     */
    public static int elementSize_data_data_wData_value() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.wData.value'
     */
    public static int elementSizeBits_data_data_wData_value() {
        return 32;
    }

    /**
     * Return the number of dimensions in the array 'data.data.wData.value'
     */
    public static int numDimensions_data_data_wData_value() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.wData.value'
     */
    public static int numElements_data_data_wData_value() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'data.data.wData.value'
     * for the given dimension.
     */
    public static int numElements_data_data_wData_value(int dimension) {
      int array_dims[] = { 2,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.level
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.level' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_level() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.level' is an array (false).
     */
    public static boolean isArray_data_data_wConfData_level() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.level'
     */
    public static int offset_data_data_wConfData_level() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.level'
     */
    public static int offsetBits_data_data_wConfData_level() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wConfData.level'
     */
    public short get_data_data_wConfData_level() {
        return (short)getUIntElement(offsetBits_data_data_wConfData_level(), 8);
    }

    /**
     * Set the value of the field 'data.data.wConfData.level'
     */
    public void set_data_data_wConfData_level(short value) {
        setUIntElement(offsetBits_data_data_wConfData_level(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wConfData.level'
     */
    public static int size_data_data_wConfData_level() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wConfData.level'
     */
    public static int sizeBits_data_data_wConfData_level() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.packNum
    //   Field type: short
    //   Offset (bits): 56
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.packNum' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_packNum() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.packNum' is an array (false).
     */
    public static boolean isArray_data_data_wConfData_packNum() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.packNum'
     */
    public static int offset_data_data_wConfData_packNum() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.packNum'
     */
    public static int offsetBits_data_data_wConfData_packNum() {
        return 56;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wConfData.packNum'
     */
    public short get_data_data_wConfData_packNum() {
        return (short)getUIntElement(offsetBits_data_data_wConfData_packNum(), 8);
    }

    /**
     * Set the value of the field 'data.data.wConfData.packNum'
     */
    public void set_data_data_wConfData_packNum(short value) {
        setUIntElement(offsetBits_data_data_wConfData_packNum(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wConfData.packNum'
     */
    public static int size_data_data_wConfData_packNum() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wConfData.packNum'
     */
    public static int sizeBits_data_data_wConfData_packNum() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.moteCount
    //   Field type: short
    //   Offset (bits): 64
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.moteCount' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_moteCount() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.moteCount' is an array (false).
     */
    public static boolean isArray_data_data_wConfData_moteCount() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.moteCount'
     */
    public static int offset_data_data_wConfData_moteCount() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.moteCount'
     */
    public static int offsetBits_data_data_wConfData_moteCount() {
        return 64;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wConfData.moteCount'
     */
    public short get_data_data_wConfData_moteCount() {
        return (short)getUIntElement(offsetBits_data_data_wConfData_moteCount(), 8);
    }

    /**
     * Set the value of the field 'data.data.wConfData.moteCount'
     */
    public void set_data_data_wConfData_moteCount(short value) {
        setUIntElement(offsetBits_data_data_wConfData_moteCount(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wConfData.moteCount'
     */
    public static int size_data_data_wConfData_moteCount() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wConfData.moteCount'
     */
    public static int sizeBits_data_data_wConfData_moteCount() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.moteConf.id
    //   Field type: short[]
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.moteConf.id' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_moteConf_id() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.moteConf.id' is an array (true).
     */
    public static boolean isArray_data_data_wConfData_moteConf_id() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.moteConf.id'
     */
    public static int offset_data_data_wConfData_moteConf_id(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.moteConf.id'
     */
    public static int offsetBits_data_data_wConfData_moteConf_id(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.wConfData.moteConf.id' as a short[]
     */
    public short[] get_data_data_wConfData_moteConf_id() {
        short[] tmp = new short[3];
        for (int index0 = 0; index0 < numElements_data_data_wConfData_moteConf_id(0); index0++) {
            tmp[index0] = getElement_data_data_wConfData_moteConf_id(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.wConfData.moteConf.id' from the given short[]
     */
    public void set_data_data_wConfData_moteConf_id(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_wConfData_moteConf_id(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data.data.wConfData.moteConf.id'
     */
    public short getElement_data_data_wConfData_moteConf_id(int index1) {
        return (short)getUIntElement(offsetBits_data_data_wConfData_moteConf_id(index1), 8);
    }

    /**
     * Set an element of the array 'data.data.wConfData.moteConf.id'
     */
    public void setElement_data_data_wConfData_moteConf_id(int index1, short value) {
        setUIntElement(offsetBits_data_data_wConfData_moteConf_id(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.wConfData.moteConf.id'
     */
    public static int totalSize_data_data_wConfData_moteConf_id() {
        return (144 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.wConfData.moteConf.id'
     */
    public static int totalSizeBits_data_data_wConfData_moteConf_id() {
        return 144;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.wConfData.moteConf.id'
     */
    public static int elementSize_data_data_wConfData_moteConf_id() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.wConfData.moteConf.id'
     */
    public static int elementSizeBits_data_data_wConfData_moteConf_id() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data.data.wConfData.moteConf.id'
     */
    public static int numDimensions_data_data_wConfData_moteConf_id() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.id'
     */
    public static int numElements_data_data_wConfData_moteConf_id() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.id'
     * for the given dimension.
     */
    public static int numElements_data_data_wConfData_moteConf_id(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data.data.wConfData.moteConf.id' with a String
     */
    public void setString_data_data_wConfData_moteConf_id(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data_data_wConfData_moteConf_id(i, (short)s.charAt(i));
         }
         setElement_data_data_wConfData_moteConf_id(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data.data.wConfData.moteConf.id' as a String
     */
    public String getString_data_data_wConfData_moteConf_id() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,3)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data_data_wConfData_moteConf_id(i) == (char)0) break;
             carr[i] = (char)getElement_data_data_wConfData_moteConf_id(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.moteConf.state
    //   Field type: short[]
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.moteConf.state' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_moteConf_state() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.moteConf.state' is an array (true).
     */
    public static boolean isArray_data_data_wConfData_moteConf_state() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.moteConf.state'
     */
    public static int offset_data_data_wConfData_moteConf_state(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.moteConf.state'
     */
    public static int offsetBits_data_data_wConfData_moteConf_state(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.wConfData.moteConf.state' as a short[]
     */
    public short[] get_data_data_wConfData_moteConf_state() {
        short[] tmp = new short[3];
        for (int index0 = 0; index0 < numElements_data_data_wConfData_moteConf_state(0); index0++) {
            tmp[index0] = getElement_data_data_wConfData_moteConf_state(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.wConfData.moteConf.state' from the given short[]
     */
    public void set_data_data_wConfData_moteConf_state(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_wConfData_moteConf_state(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data.data.wConfData.moteConf.state'
     */
    public short getElement_data_data_wConfData_moteConf_state(int index1) {
        return (short)getUIntElement(offsetBits_data_data_wConfData_moteConf_state(index1), 8);
    }

    /**
     * Set an element of the array 'data.data.wConfData.moteConf.state'
     */
    public void setElement_data_data_wConfData_moteConf_state(int index1, short value) {
        setUIntElement(offsetBits_data_data_wConfData_moteConf_state(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.wConfData.moteConf.state'
     */
    public static int totalSize_data_data_wConfData_moteConf_state() {
        return (144 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.wConfData.moteConf.state'
     */
    public static int totalSizeBits_data_data_wConfData_moteConf_state() {
        return 144;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.wConfData.moteConf.state'
     */
    public static int elementSize_data_data_wConfData_moteConf_state() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.wConfData.moteConf.state'
     */
    public static int elementSizeBits_data_data_wConfData_moteConf_state() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data.data.wConfData.moteConf.state'
     */
    public static int numDimensions_data_data_wConfData_moteConf_state() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.state'
     */
    public static int numElements_data_data_wConfData_moteConf_state() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.state'
     * for the given dimension.
     */
    public static int numElements_data_data_wConfData_moteConf_state(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data.data.wConfData.moteConf.state' with a String
     */
    public void setString_data_data_wConfData_moteConf_state(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data_data_wConfData_moteConf_state(i, (short)s.charAt(i));
         }
         setElement_data_data_wConfData_moteConf_state(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data.data.wConfData.moteConf.state' as a String
     */
    public String getString_data_data_wConfData_moteConf_state() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,3)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data_data_wConfData_moteConf_state(i) == (char)0) break;
             carr[i] = (char)getElement_data_data_wConfData_moteConf_state(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfData.moteConf.coeff
    //   Field type: float[]
    //   Offset (bits): 16
    //   Size of each element (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfData.moteConf.coeff' is signed (false).
     */
    public static boolean isSigned_data_data_wConfData_moteConf_coeff() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfData.moteConf.coeff' is an array (true).
     */
    public static boolean isArray_data_data_wConfData_moteConf_coeff() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfData.moteConf.coeff'
     */
    public static int offset_data_data_wConfData_moteConf_coeff(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfData.moteConf.coeff'
     */
    public static int offsetBits_data_data_wConfData_moteConf_coeff(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 3) throw new ArrayIndexOutOfBoundsException();
        offset += 72 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.wConfData.moteConf.coeff' as a float[]
     */
    public float[] get_data_data_wConfData_moteConf_coeff() {
        float[] tmp = new float[3];
        for (int index0 = 0; index0 < numElements_data_data_wConfData_moteConf_coeff(0); index0++) {
            tmp[index0] = getElement_data_data_wConfData_moteConf_coeff(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.wConfData.moteConf.coeff' from the given float[]
     */
    public void set_data_data_wConfData_moteConf_coeff(float[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_wConfData_moteConf_coeff(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a float) of the array 'data.data.wConfData.moteConf.coeff'
     */
    public float getElement_data_data_wConfData_moteConf_coeff(int index1) {
        return (float)getFloatElement(offsetBits_data_data_wConfData_moteConf_coeff(index1), 32);
    }

    /**
     * Set an element of the array 'data.data.wConfData.moteConf.coeff'
     */
    public void setElement_data_data_wConfData_moteConf_coeff(int index1, float value) {
        setFloatElement(offsetBits_data_data_wConfData_moteConf_coeff(index1), 32, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int totalSize_data_data_wConfData_moteConf_coeff() {
        return (144 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int totalSizeBits_data_data_wConfData_moteConf_coeff() {
        return 144;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int elementSize_data_data_wConfData_moteConf_coeff() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int elementSizeBits_data_data_wConfData_moteConf_coeff() {
        return 32;
    }

    /**
     * Return the number of dimensions in the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int numDimensions_data_data_wConfData_moteConf_coeff() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.coeff'
     */
    public static int numElements_data_data_wConfData_moteConf_coeff() {
        return 3;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfData.moteConf.coeff'
     * for the given dimension.
     */
    public static int numElements_data_data_wConfData_moteConf_coeff(int dimension) {
      int array_dims[] = { 3,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfHeader.numLevels
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfHeader.numLevels' is signed (false).
     */
    public static boolean isSigned_data_data_wConfHeader_numLevels() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfHeader.numLevels' is an array (false).
     */
    public static boolean isArray_data_data_wConfHeader_numLevels() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfHeader.numLevels'
     */
    public static int offset_data_data_wConfHeader_numLevels() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfHeader.numLevels'
     */
    public static int offsetBits_data_data_wConfHeader_numLevels() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wConfHeader.numLevels'
     */
    public short get_data_data_wConfHeader_numLevels() {
        return (short)getUIntElement(offsetBits_data_data_wConfHeader_numLevels(), 8);
    }

    /**
     * Set the value of the field 'data.data.wConfHeader.numLevels'
     */
    public void set_data_data_wConfHeader_numLevels(short value) {
        setUIntElement(offsetBits_data_data_wConfHeader_numLevels(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wConfHeader.numLevels'
     */
    public static int size_data_data_wConfHeader_numLevels() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wConfHeader.numLevels'
     */
    public static int sizeBits_data_data_wConfHeader_numLevels() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wConfHeader.nbCount
    //   Field type: short[]
    //   Offset (bits): 56
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wConfHeader.nbCount' is signed (false).
     */
    public static boolean isSigned_data_data_wConfHeader_nbCount() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wConfHeader.nbCount' is an array (true).
     */
    public static boolean isArray_data_data_wConfHeader_nbCount() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wConfHeader.nbCount'
     */
    public static int offset_data_data_wConfHeader_nbCount(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wConfHeader.nbCount'
     */
    public static int offsetBits_data_data_wConfHeader_nbCount(int index1) {
        int offset = 56;
        if (index1 < 0 || index1 >= 10) throw new ArrayIndexOutOfBoundsException();
        offset += 0 + index1 * 8;
        return offset;
    }

    /**
     * Return the entire array 'data.data.wConfHeader.nbCount' as a short[]
     */
    public short[] get_data_data_wConfHeader_nbCount() {
        short[] tmp = new short[10];
        for (int index0 = 0; index0 < numElements_data_data_wConfHeader_nbCount(0); index0++) {
            tmp[index0] = getElement_data_data_wConfHeader_nbCount(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.wConfHeader.nbCount' from the given short[]
     */
    public void set_data_data_wConfHeader_nbCount(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_wConfHeader_nbCount(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data.data.wConfHeader.nbCount'
     */
    public short getElement_data_data_wConfHeader_nbCount(int index1) {
        return (short)getUIntElement(offsetBits_data_data_wConfHeader_nbCount(index1), 8);
    }

    /**
     * Set an element of the array 'data.data.wConfHeader.nbCount'
     */
    public void setElement_data_data_wConfHeader_nbCount(int index1, short value) {
        setUIntElement(offsetBits_data_data_wConfHeader_nbCount(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.wConfHeader.nbCount'
     */
    public static int totalSize_data_data_wConfHeader_nbCount() {
        return (80 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.wConfHeader.nbCount'
     */
    public static int totalSizeBits_data_data_wConfHeader_nbCount() {
        return 80;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.wConfHeader.nbCount'
     */
    public static int elementSize_data_data_wConfHeader_nbCount() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.wConfHeader.nbCount'
     */
    public static int elementSizeBits_data_data_wConfHeader_nbCount() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data.data.wConfHeader.nbCount'
     */
    public static int numDimensions_data_data_wConfHeader_nbCount() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfHeader.nbCount'
     */
    public static int numElements_data_data_wConfHeader_nbCount() {
        return 10;
    }

    /**
     * Return the number of elements in the array 'data.data.wConfHeader.nbCount'
     * for the given dimension.
     */
    public static int numElements_data_data_wConfHeader_nbCount(int dimension) {
      int array_dims[] = { 10,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data.data.wConfHeader.nbCount' with a String
     */
    public void setString_data_data_wConfHeader_nbCount(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data_data_wConfHeader_nbCount(i, (short)s.charAt(i));
         }
         setElement_data_data_wConfHeader_nbCount(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data.data.wConfHeader.nbCount' as a String
     */
    public String getString_data_data_wConfHeader_nbCount() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,10)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data_data_wConfHeader_nbCount(i) == (char)0) break;
             carr[i] = (char)getElement_data_data_wConfHeader_nbCount(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wState.state
    //   Field type: short
    //   Offset (bits): 48
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wState.state' is signed (false).
     */
    public static boolean isSigned_data_data_wState_state() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wState.state' is an array (false).
     */
    public static boolean isArray_data_data_wState_state() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wState.state'
     */
    public static int offset_data_data_wState_state() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wState.state'
     */
    public static int offsetBits_data_data_wState_state() {
        return 48;
    }

    /**
     * Return the value (as a short) of the field 'data.data.wState.state'
     */
    public short get_data_data_wState_state() {
        return (short)getUIntElement(offsetBits_data_data_wState_state(), 8);
    }

    /**
     * Set the value of the field 'data.data.wState.state'
     */
    public void set_data_data_wState_state(short value) {
        setUIntElement(offsetBits_data_data_wState_state(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wState.state'
     */
    public static int size_data_data_wState_state() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wState.state'
     */
    public static int sizeBits_data_data_wState_state() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.wState.dataSetTime
    //   Field type: long
    //   Offset (bits): 56
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.wState.dataSetTime' is signed (false).
     */
    public static boolean isSigned_data_data_wState_dataSetTime() {
        return false;
    }

    /**
     * Return whether the field 'data.data.wState.dataSetTime' is an array (false).
     */
    public static boolean isArray_data_data_wState_dataSetTime() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.wState.dataSetTime'
     */
    public static int offset_data_data_wState_dataSetTime() {
        return (56 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.wState.dataSetTime'
     */
    public static int offsetBits_data_data_wState_dataSetTime() {
        return 56;
    }

    /**
     * Return the value (as a long) of the field 'data.data.wState.dataSetTime'
     */
    public long get_data_data_wState_dataSetTime() {
        return (long)getUIntElement(offsetBits_data_data_wState_dataSetTime(), 32);
    }

    /**
     * Set the value of the field 'data.data.wState.dataSetTime'
     */
    public void set_data_data_wState_dataSetTime(long value) {
        setUIntElement(offsetBits_data_data_wState_dataSetTime(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.wState.dataSetTime'
     */
    public static int size_data_data_wState_dataSetTime() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.wState.dataSetTime'
     */
    public static int sizeBits_data_data_wState_dataSetTime() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.rcvd
    //   Field type: int
    //   Offset (bits): 48
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.rcvd' is signed (false).
     */
    public static boolean isSigned_data_data_stats_rcvd() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.rcvd' is an array (false).
     */
    public static boolean isArray_data_data_stats_rcvd() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.rcvd'
     */
    public static int offset_data_data_stats_rcvd() {
        return (48 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.rcvd'
     */
    public static int offsetBits_data_data_stats_rcvd() {
        return 48;
    }

    /**
     * Return the value (as a int) of the field 'data.data.stats.rcvd'
     */
    public int get_data_data_stats_rcvd() {
        return (int)getUIntElement(offsetBits_data_data_stats_rcvd(), 16);
    }

    /**
     * Set the value of the field 'data.data.stats.rcvd'
     */
    public void set_data_data_stats_rcvd(int value) {
        setUIntElement(offsetBits_data_data_stats_rcvd(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.stats.rcvd'
     */
    public static int size_data_data_stats_rcvd() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.stats.rcvd'
     */
    public static int sizeBits_data_data_stats_rcvd() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.rssi
    //   Field type: float
    //   Offset (bits): 64
    //   Size (bits): 32
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.rssi' is signed (false).
     */
    public static boolean isSigned_data_data_stats_rssi() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.rssi' is an array (false).
     */
    public static boolean isArray_data_data_stats_rssi() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.rssi'
     */
    public static int offset_data_data_stats_rssi() {
        return (64 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.rssi'
     */
    public static int offsetBits_data_data_stats_rssi() {
        return 64;
    }

    /**
     * Return the value (as a float) of the field 'data.data.stats.rssi'
     */
    public float get_data_data_stats_rssi() {
        return (float)getFloatElement(offsetBits_data_data_stats_rssi(), 32);
    }

    /**
     * Set the value of the field 'data.data.stats.rssi'
     */
    public void set_data_data_stats_rssi(float value) {
        setFloatElement(offsetBits_data_data_stats_rssi(), 32, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.stats.rssi'
     */
    public static int size_data_data_stats_rssi() {
        return (32 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.stats.rssi'
     */
    public static int sizeBits_data_data_stats_rssi() {
        return 32;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.sent
    //   Field type: int
    //   Offset (bits): 96
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.sent' is signed (false).
     */
    public static boolean isSigned_data_data_stats_sent() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.sent' is an array (false).
     */
    public static boolean isArray_data_data_stats_sent() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.sent'
     */
    public static int offset_data_data_stats_sent() {
        return (96 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.sent'
     */
    public static int offsetBits_data_data_stats_sent() {
        return 96;
    }

    /**
     * Return the value (as a int) of the field 'data.data.stats.sent'
     */
    public int get_data_data_stats_sent() {
        return (int)getUIntElement(offsetBits_data_data_stats_sent(), 16);
    }

    /**
     * Set the value of the field 'data.data.stats.sent'
     */
    public void set_data_data_stats_sent(int value) {
        setUIntElement(offsetBits_data_data_stats_sent(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.stats.sent'
     */
    public static int size_data_data_stats_sent() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.stats.sent'
     */
    public static int sizeBits_data_data_stats_sent() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.acked
    //   Field type: int
    //   Offset (bits): 112
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.acked' is signed (false).
     */
    public static boolean isSigned_data_data_stats_acked() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.acked' is an array (false).
     */
    public static boolean isArray_data_data_stats_acked() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.acked'
     */
    public static int offset_data_data_stats_acked() {
        return (112 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.acked'
     */
    public static int offsetBits_data_data_stats_acked() {
        return 112;
    }

    /**
     * Return the value (as a int) of the field 'data.data.stats.acked'
     */
    public int get_data_data_stats_acked() {
        return (int)getUIntElement(offsetBits_data_data_stats_acked(), 16);
    }

    /**
     * Set the value of the field 'data.data.stats.acked'
     */
    public void set_data_data_stats_acked(int value) {
        setUIntElement(offsetBits_data_data_stats_acked(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.stats.acked'
     */
    public static int size_data_data_stats_acked() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.stats.acked'
     */
    public static int sizeBits_data_data_stats_acked() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.numReps
    //   Field type: short
    //   Offset (bits): 128
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.numReps' is signed (false).
     */
    public static boolean isSigned_data_data_stats_numReps() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.numReps' is an array (false).
     */
    public static boolean isArray_data_data_stats_numReps() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.numReps'
     */
    public static int offset_data_data_stats_numReps() {
        return (128 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.numReps'
     */
    public static int offsetBits_data_data_stats_numReps() {
        return 128;
    }

    /**
     * Return the value (as a short) of the field 'data.data.stats.numReps'
     */
    public short get_data_data_stats_numReps() {
        return (short)getUIntElement(offsetBits_data_data_stats_numReps(), 8);
    }

    /**
     * Set the value of the field 'data.data.stats.numReps'
     */
    public void set_data_data_stats_numReps(short value) {
        setUIntElement(offsetBits_data_data_stats_numReps(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'data.data.stats.numReps'
     */
    public static int size_data_data_stats_numReps() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'data.data.stats.numReps'
     */
    public static int sizeBits_data_data_stats_numReps() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.reports.type
    //   Field type: short[]
    //   Offset (bits): 0
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.reports.type' is signed (false).
     */
    public static boolean isSigned_data_data_stats_reports_type() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.reports.type' is an array (true).
     */
    public static boolean isArray_data_data_stats_reports_type() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.reports.type'
     */
    public static int offset_data_data_stats_reports_type(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.reports.type'
     */
    public static int offsetBits_data_data_stats_reports_type(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.stats.reports.type' as a short[]
     */
    public short[] get_data_data_stats_reports_type() {
        short[] tmp = new short[2];
        for (int index0 = 0; index0 < numElements_data_data_stats_reports_type(0); index0++) {
            tmp[index0] = getElement_data_data_stats_reports_type(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.stats.reports.type' from the given short[]
     */
    public void set_data_data_stats_reports_type(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_stats_reports_type(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data.data.stats.reports.type'
     */
    public short getElement_data_data_stats_reports_type(int index1) {
        return (short)getUIntElement(offsetBits_data_data_stats_reports_type(index1), 8);
    }

    /**
     * Set an element of the array 'data.data.stats.reports.type'
     */
    public void setElement_data_data_stats_reports_type(int index1, short value) {
        setUIntElement(offsetBits_data_data_stats_reports_type(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.stats.reports.type'
     */
    public static int totalSize_data_data_stats_reports_type() {
        return (96 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.stats.reports.type'
     */
    public static int totalSizeBits_data_data_stats_reports_type() {
        return 96;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.stats.reports.type'
     */
    public static int elementSize_data_data_stats_reports_type() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.stats.reports.type'
     */
    public static int elementSizeBits_data_data_stats_reports_type() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data.data.stats.reports.type'
     */
    public static int numDimensions_data_data_stats_reports_type() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.type'
     */
    public static int numElements_data_data_stats_reports_type() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.type'
     * for the given dimension.
     */
    public static int numElements_data_data_stats_reports_type(int dimension) {
      int array_dims[] = { 2,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data.data.stats.reports.type' with a String
     */
    public void setString_data_data_stats_reports_type(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data_data_stats_reports_type(i, (short)s.charAt(i));
         }
         setElement_data_data_stats_reports_type(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data.data.stats.reports.type' as a String
     */
    public String getString_data_data_stats_reports_type() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,2)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data_data_stats_reports_type(i) == (char)0) break;
             carr[i] = (char)getElement_data_data_stats_reports_type(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.reports.data.cache.level
    //   Field type: short[]
    //   Offset (bits): 8
    //   Size of each element (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.reports.data.cache.level' is signed (false).
     */
    public static boolean isSigned_data_data_stats_reports_data_cache_level() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.reports.data.cache.level' is an array (true).
     */
    public static boolean isArray_data_data_stats_reports_data_cache_level() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.reports.data.cache.level'
     */
    public static int offset_data_data_stats_reports_data_cache_level(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.reports.data.cache.level'
     */
    public static int offsetBits_data_data_stats_reports_data_cache_level(int index1) {
        int offset = 8;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.stats.reports.data.cache.level' as a short[]
     */
    public short[] get_data_data_stats_reports_data_cache_level() {
        short[] tmp = new short[2];
        for (int index0 = 0; index0 < numElements_data_data_stats_reports_data_cache_level(0); index0++) {
            tmp[index0] = getElement_data_data_stats_reports_data_cache_level(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.stats.reports.data.cache.level' from the given short[]
     */
    public void set_data_data_stats_reports_data_cache_level(short[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_stats_reports_data_cache_level(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a short) of the array 'data.data.stats.reports.data.cache.level'
     */
    public short getElement_data_data_stats_reports_data_cache_level(int index1) {
        return (short)getUIntElement(offsetBits_data_data_stats_reports_data_cache_level(index1), 8);
    }

    /**
     * Set an element of the array 'data.data.stats.reports.data.cache.level'
     */
    public void setElement_data_data_stats_reports_data_cache_level(int index1, short value) {
        setUIntElement(offsetBits_data_data_stats_reports_data_cache_level(index1), 8, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.stats.reports.data.cache.level'
     */
    public static int totalSize_data_data_stats_reports_data_cache_level() {
        return (96 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.stats.reports.data.cache.level'
     */
    public static int totalSizeBits_data_data_stats_reports_data_cache_level() {
        return 96;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.stats.reports.data.cache.level'
     */
    public static int elementSize_data_data_stats_reports_data_cache_level() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.stats.reports.data.cache.level'
     */
    public static int elementSizeBits_data_data_stats_reports_data_cache_level() {
        return 8;
    }

    /**
     * Return the number of dimensions in the array 'data.data.stats.reports.data.cache.level'
     */
    public static int numDimensions_data_data_stats_reports_data_cache_level() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.data.cache.level'
     */
    public static int numElements_data_data_stats_reports_data_cache_level() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.data.cache.level'
     * for the given dimension.
     */
    public static int numElements_data_data_stats_reports_data_cache_level(int dimension) {
      int array_dims[] = { 2,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /**
     * Fill in the array 'data.data.stats.reports.data.cache.level' with a String
     */
    public void setString_data_data_stats_reports_data_cache_level(String s) { 
         int len = s.length();
         int i;
         for (i = 0; i < len; i++) {
             setElement_data_data_stats_reports_data_cache_level(i, (short)s.charAt(i));
         }
         setElement_data_data_stats_reports_data_cache_level(i, (short)0); //null terminate
    }

    /**
     * Read the array 'data.data.stats.reports.data.cache.level' as a String
     */
    public String getString_data_data_stats_reports_data_cache_level() { 
         char carr[] = new char[Math.min(net.tinyos.message.Message.MAX_CONVERTED_STRING_LENGTH,2)];
         int i;
         for (i = 0; i < carr.length; i++) {
             if ((char)getElement_data_data_stats_reports_data_cache_level(i) == (char)0) break;
             carr[i] = (char)getElement_data_data_stats_reports_data_cache_level(i);
         }
         return new String(carr,0,i);
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.reports.data.cache.mote
    //   Field type: int[]
    //   Offset (bits): 16
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.reports.data.cache.mote' is signed (false).
     */
    public static boolean isSigned_data_data_stats_reports_data_cache_mote() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.reports.data.cache.mote' is an array (true).
     */
    public static boolean isArray_data_data_stats_reports_data_cache_mote() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.reports.data.cache.mote'
     */
    public static int offset_data_data_stats_reports_data_cache_mote(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.reports.data.cache.mote'
     */
    public static int offsetBits_data_data_stats_reports_data_cache_mote(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.stats.reports.data.cache.mote' as a int[]
     */
    public int[] get_data_data_stats_reports_data_cache_mote() {
        int[] tmp = new int[2];
        for (int index0 = 0; index0 < numElements_data_data_stats_reports_data_cache_mote(0); index0++) {
            tmp[index0] = getElement_data_data_stats_reports_data_cache_mote(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.stats.reports.data.cache.mote' from the given int[]
     */
    public void set_data_data_stats_reports_data_cache_mote(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_stats_reports_data_cache_mote(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data.data.stats.reports.data.cache.mote'
     */
    public int getElement_data_data_stats_reports_data_cache_mote(int index1) {
        return (int)getUIntElement(offsetBits_data_data_stats_reports_data_cache_mote(index1), 16);
    }

    /**
     * Set an element of the array 'data.data.stats.reports.data.cache.mote'
     */
    public void setElement_data_data_stats_reports_data_cache_mote(int index1, int value) {
        setUIntElement(offsetBits_data_data_stats_reports_data_cache_mote(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int totalSize_data_data_stats_reports_data_cache_mote() {
        return (96 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int totalSizeBits_data_data_stats_reports_data_cache_mote() {
        return 96;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int elementSize_data_data_stats_reports_data_cache_mote() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int elementSizeBits_data_data_stats_reports_data_cache_mote() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int numDimensions_data_data_stats_reports_data_cache_mote() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.data.cache.mote'
     */
    public static int numElements_data_data_stats_reports_data_cache_mote() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.data.cache.mote'
     * for the given dimension.
     */
    public static int numElements_data_data_stats_reports_data_cache_mote(int dimension) {
      int array_dims[] = { 2,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: data.data.stats.reports.number
    //   Field type: int[]
    //   Offset (bits): 32
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'data.data.stats.reports.number' is signed (false).
     */
    public static boolean isSigned_data_data_stats_reports_number() {
        return false;
    }

    /**
     * Return whether the field 'data.data.stats.reports.number' is an array (true).
     */
    public static boolean isArray_data_data_stats_reports_number() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'data.data.stats.reports.number'
     */
    public static int offset_data_data_stats_reports_number(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'data.data.stats.reports.number'
     */
    public static int offsetBits_data_data_stats_reports_number(int index1) {
        int offset = 32;
        if (index1 < 0 || index1 >= 2) throw new ArrayIndexOutOfBoundsException();
        offset += 136 + index1 * 48;
        return offset;
    }

    /**
     * Return the entire array 'data.data.stats.reports.number' as a int[]
     */
    public int[] get_data_data_stats_reports_number() {
        int[] tmp = new int[2];
        for (int index0 = 0; index0 < numElements_data_data_stats_reports_number(0); index0++) {
            tmp[index0] = getElement_data_data_stats_reports_number(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'data.data.stats.reports.number' from the given int[]
     */
    public void set_data_data_stats_reports_number(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_data_data_stats_reports_number(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'data.data.stats.reports.number'
     */
    public int getElement_data_data_stats_reports_number(int index1) {
        return (int)getUIntElement(offsetBits_data_data_stats_reports_number(index1), 16);
    }

    /**
     * Set an element of the array 'data.data.stats.reports.number'
     */
    public void setElement_data_data_stats_reports_number(int index1, int value) {
        setUIntElement(offsetBits_data_data_stats_reports_number(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'data.data.stats.reports.number'
     */
    public static int totalSize_data_data_stats_reports_number() {
        return (96 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'data.data.stats.reports.number'
     */
    public static int totalSizeBits_data_data_stats_reports_number() {
        return 96;
    }

    /**
     * Return the size, in bytes, of each element of the array 'data.data.stats.reports.number'
     */
    public static int elementSize_data_data_stats_reports_number() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'data.data.stats.reports.number'
     */
    public static int elementSizeBits_data_data_stats_reports_number() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'data.data.stats.reports.number'
     */
    public static int numDimensions_data_data_stats_reports_number() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.number'
     */
    public static int numElements_data_data_stats_reports_number() {
        return 2;
    }

    /**
     * Return the number of elements in the array 'data.data.stats.reports.number'
     * for the given dimension.
     */
    public static int numElements_data_data_stats_reports_number(int dimension) {
      int array_dims[] = { 2,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
